/**
 * Header
 */
const ACTION_TYPE_HEADER_LOGIN = 'ACTION_TYPE_HEADER_LOGIN';
const ACTION_TYPE_HEADER_SELECT = 'ACTION_TYPE_HEADER_SELECT';


/**
 * Upload
 */
const ACTION_TYPE_UPLOAD_SELECT_FILE = 'ACTION_TYPE_UPLOAD_SELECT_FILE';
const ACTION_TYPE_UPLOAD_OPTIONS_CHANGE = 'ACTION_TYPE_UPLOAD_OPTIONS_CHANGE';
const ACTION_TYPE_UPDATE_STATE = 'ACTION_TYPE_UPDATE_STATE';
const ACTION_TYPE_BEGIN_UPLOAD = 'ACTION_TYPE_BEGIN_UPLOAD';
const ACTION_TYPE_UPLOAD_PROGRESS = 'ACTION_TYPE_UPLOAD_PROGRESS';
const ACTION_TYPE_UPLOAD_ERR = 'ACTION_TYPE_UPLOAD_ERR';
const ACTION_TYPE_UPLOAD_SUCCESS = 'ACTION_TYPE_UPLOAD_SUCCESS';

/**
 * Square
 */
const ACTION_TYPE_SQUARE_LOAD = 'ACTION_TYPE_SQUARE_LOAD';
const ACTION_TYPE_SQUARE_LOAD_FINISH = 'ACTION_TYPE_SQUARE_LOAD_FINISH';
const ACTION_TYPE_CHANGE_CATEGORY = 'ACTION_TYPE_CHANGE_CATEGORY';

export {
    ACTION_TYPE_HEADER_LOGIN,
    ACTION_TYPE_HEADER_SELECT,
    ACTION_TYPE_UPLOAD_SELECT_FILE,
    ACTION_TYPE_UPLOAD_OPTIONS_CHANGE,
    ACTION_TYPE_UPDATE_STATE,
    ACTION_TYPE_UPLOAD_PROGRESS,
    ACTION_TYPE_UPLOAD_ERR,
    ACTION_TYPE_UPLOAD_SUCCESS,
    ACTION_TYPE_SQUARE_LOAD,
    ACTION_TYPE_SQUARE_LOAD_FINISH,
    ACTION_TYPE_BEGIN_UPLOAD,
    ACTION_TYPE_CHANGE_CATEGORY
}