/**
 * Header
 */
const ACTION_TYPE_HEADER_LOGIN = 'ACTION_TYPE_HEADER_LOGIN';
const ACTION_TYPE_HEADER_SELECT = 'ACTION_TYPE_HEADER_SELECT';
export {
    ACTION_TYPE_HEADER_LOGIN,
    ACTION_TYPE_HEADER_SELECT
}