/**
 * Header
 */
const ACTION_TYPE_HEADER_LOGIN = 'ACTION_TYPE_HEADER_LOGIN';
const ACTION_TYPE_HEADER_SELECT = 'ACTION_TYPE_HEADER_SELECT';


/**
 * Upload
 */
const ACTION_TYPE_UPLOAD_SELECT_FILE = 'ACTION_TYPE_UPLOAD_SELECT_FILE';
const ACTION_TYPE_UPLOAD_OPTIONS_CHANGE = 'ACTION_TYPE_UPLOAD_OPTIONS_CHANGE';
const ACTION_TYPE_UPDATE_STATE = 'ACTION_TYPE_UPDATE_STATE';

export {
    ACTION_TYPE_HEADER_LOGIN,
    ACTION_TYPE_HEADER_SELECT,
    ACTION_TYPE_UPLOAD_SELECT_FILE,
    ACTION_TYPE_UPLOAD_OPTIONS_CHANGE,
    ACTION_TYPE_UPDATE_STATE,
}